project:
  type: website
website:
  title: "![](supporting_images/logo_small.png)"
  page-navigation: true
  sidebar:
    search: true
    contents:
      - href: index.qmd
        text: Home
      - intro.qmd
      

bibliography: references.bib
format:
  html:
    toc: true
    theme: [cosmo,custom.scss]
    logo: "supporting_images/logo_small.png"
    number-depth: 2
    css: include/webex.css
    include-after-body: include/webex.js
editor: source

# https://github.com/EllaKaye/ellakaye.co.uk/blob/main/_quarto.yml
# https://ucsb-meds.github.io/customizing-quarto-websites/#/title-slide
# Ideas for improvement